"""initial

Revision ID: 7ebb3fc55bcd
Revises: 
Create Date: 2024-12-16 14:30:46.011350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebb3fc55bcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('person')
    # ### end Alembic commands ###
